apiVersion: apps/v1
kind: Deployment
metadata:
  name: drugs-data-deployment
  labels:
    app: drugs-data
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drugs-data
  template:
    metadata:
      labels:
        app: drugs-data
    spec:
      containers:
      - name: drugs-data
        image: uaimpw/drugs-data-microservice	
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://+
---
apiVersion: v1
kind: Service
metadata:
  name: drugs-data-service
spec:
  selector:
    app: drugs-data
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30003