apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients-application-deployment
  labels:
    app: patients-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patients-application
  template:
    metadata:
      labels:
        app: patients-application
    spec:
      containers:
      - name: patients-application
        image: uaimpw/patient-application-microservice	
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://+
        - name: AppConfig__PrescriptionDataBaseUrl
          valueFrom:
            configMapKeyRef: 
              name: app-configmap
              key: prescriptions-data_url
        - name: AppConfig__PatientDataBaseUrl
          valueFrom:
            configMapKeyRef: 
              name: app-configmap
              key: patients-data_url
        - name: AppConfig__DoctorDataBaseUrl
          valueFrom:
            configMapKeyRef: 
              name: app-configmap
              key: doctors-data_url
        - name: AppConfig__DrugDataBaseUrl
          valueFrom:
            configMapKeyRef: 
              name: app-configmap
              key: drugs-data_url
---
apiVersion: v1
kind: Service
metadata:
  name: patients-application-microservice
spec:
  selector:
    app: patients-application
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30004